---
  - name: Config Elk
    hosts: Elk
    become: true
    tasks:
	- name: docker.io
	  apt:
	    update_cache: yes
	    name: docker.io
	    state: present
	- name: Install pip
	  apt:
	    name: python3-pip
	    state: present
	- name: Use more memory
	  sysctl:
	    name: vm.max_map_count
	    value: '262144'
	    state: present
	    reload: yes
	- nmae: Install Docker python module
	  pip:
	    name: docker
	    state present
	- name: download and launch elk container
	  docker_container:
	     name: elk
	     image: sebp/elk:740
	     state: started
	     restart_policy: alwaes
	     published_ports:
		- 5601;5601
		- 9200:9200
		- 5044:5044
	- name: Enable docker service
	  systemd:
	      name: docker
	      enabled: yes
